apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: react-app
  name: react-node-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: react-app
    spec:
      containers:
      - image: cooldsachin/react-app
        name: react-app
        ports:
        - name: react-app
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: react-app
  name: react-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: react-app
---
